Step implementation
bitrise-steplib/step-custom-test-results-export pull request #1
Opened 2020-03-05 15:07 UTC by Szabadember

This PR implements the custom test result export step

2020-03-05 15:30 UTC, godrei requested changes
pls check my notes

2020-03-05 15:30 UTC, godrei commented on Gopkg.toml
> +[[constraint]]
pls remove template code

2020-03-05 15:30 UTC, godrei commented on LICENSE
> +Copyright (c) 2020 Áron Szabados
Copyright (c) 2020 Bitrise

2020-03-05 15:30 UTC, godrei commented on bitrise.yml
> +format_version: 4
pls use the latest format version ([10](https://github.com/bitrise-io/bitrise/blob/master/models/models.go#L23)) to be able to benefit the new version lock (later)

2020-03-05 15:30 UTC, godrei commented on bitrise.yml
> +  - A_SECRET_PARAM: $A_SECRET_PARAM
pls remove template code

2020-03-05 15:30 UTC, godrei commented on bitrise.yml
> +  share-this-step:
we use tooling control center Bitrise project as a centralized release process, so no need to define the release process in the step repo

2020-03-05 15:30 UTC, godrei commented on bitrise.yml
> +  test:
before_run:
- audit-this-step

2020-03-05 15:30 UTC, godrei commented on config.go
> +
why the empty line here?

2020-03-05 15:30 UTC, godrei commented on config.go
> +	TestResultsDir string `env:"bitrise_test_result_dir,required"`
there is a `dir` struct field tag, which also validates if the given dir exists or not

2020-03-05 15:30 UTC, godrei commented on main.go
> +		failf("Invalid search path %s, error: %s", stepConf.SearchPath, err)
do not use the `, error:` suffix, simple write: `Invalid search path %s: %s`

2020-03-05 15:30 UTC, godrei commented on main.go
> +		failf("Search path did not match any files, path: %s", stepConf.SearchPath)
Search path %s did not match any files

2020-03-05 15:30 UTC, godrei commented on main.go
> +		log.Warnf("Search path matched more than one file, will use the first match, matches: %s", matches)
default slice String method is not the nicest format.
as Tomi suggested, have something like this:

Search path matched more than one file, will use the first match:
- **match1**
- match2
- match3

highlight the first item with green color.

2020-03-05 15:30 UTC, godrei commented on main.go
> +	os.Exit(0)
no need for this line

2020-03-05 15:30 UTC, godrei commented on step.yml
> +#
pls remove template code

2020-03-05 15:30 UTC, godrei commented on step.yml
> +type_tags:
for now, we use test tag for steps executing tests, instead, use utility

2020-03-05 15:30 UTC, godrei commented on step.yml
> +is_always_run: false
set it to true (if a test fails we still want to export the results)

2020-03-05 15:30 UTC, godrei commented on step.yml
> +deps:
pls remove unused deps

2020-03-05 15:30 UTC, godrei commented on step.yml
> +  - test_name: Custom test result
pls do not set a default for this input (users will not realize that they need to set it)

2020-03-05 15:30 UTC, godrei commented on step.yml
> +        This is the text displayed on the tab of the Test Reports page.
the description is optional if it is the same, it is better to remove

2020-03-05 15:30 UTC, godrei commented on testresultexport/testresultexport.go
> +func generateTestInfoFile(dir string, data []byte) error {
fileutil already has this functionality: https://github.com/bitrise-io/go-utils/blob/master/fileutil/fileutil.go

2020-03-05 15:30 UTC, godrei commented on testresultexport/testresultexport.go
> +func copy(src, dst string) error {
we already have this functionality: https://github.com/bitrise-io/go-utils/blob/master/command/file.go#L12

2020-03-05 15:30 UTC, godrei commented on testresultexport/testresultexport.go
> +	testResultExportName := filepath.Join(exportDir, testResultName)
extension should be kept

2020-03-05 15:30 UTC, godrei commented on testresultexport/testresultexport.go
> +	err = e.Copy(testResultPath, testResultExportName)
could be: `return e.Copy(testResultPath, testResultExportName)`

2020-03-06 16:13 UTC, Szabadember commented
test this please

2020-03-10 13:18 UTC, trapacska requested changes

2020-03-10 13:18 UTC, trapacska commented on bitrise.yml
> +            github.com/bitrise-steplib/step-custom-test-results-export/testresultexport
we have a legacy: `steps-` and the new `bitrise-step-` prefix for our step repos. please keep on going with the new one.
please dont forget to rewerite everywhaere

2020-03-10 13:18 UTC, trapacska commented on config.go
> +type Config struct {
pls do not export this as it is unnecessary

2020-03-10 13:18 UTC, trapacska commented on config.go
> +	Pattern        string `env:"pattern,required"`
not really talkative "pattern" what about `search_pattern` or maybe something more talkative. dont forget to modify it in the syep.yml also

2020-03-10 13:18 UTC, trapacska commented on main.go
> +		failf("Config: %s", err)
the error message this package returns matches with the prefix: `Issue with input:`

2020-03-10 13:18 UTC, trapacska commented on main.go
> +	matches := []string{}
NOTE: `var matches []string`

2020-03-10 13:18 UTC, trapacska commented on main.go
> +	err := filepath.Walk(basePath, func(path string, info os.FileInfo, err error) error {
NOTE: you can move this into the if

2020-03-10 13:57 UTC, trapacska requested changes
also pls add check for the output

2020-03-10 13:57 UTC, trapacska commented on step.yml
> +  - base_path:
please set `$BITRISE_SOURCE_DIR` as default input

2020-03-10 15:16 UTC, trapacska approved these changes

2020-03-10 15:16 UTC, merged